<a href="https://colab.research.google.com/github/debangan13/SIT/blob/main/ml_training_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Numpy
# Author : Satyam Kumar Jha

In [ ]:
# Creating 0-d array using numpy
import numpy as np
zeroDimensionArray = np.array(100)
print("This is my 0-d array ")
print(zeroDimensionArray)
print("The dimension of this array is  ",zeroDimensionArray.ndim)

This is my 0-d array 
100
The dimension of this array is   0


In [ ]:
# Creating 1-d array
import numpy as np
oneDimensionArray = np.array([1,2,3,4,5])
print("This is my one dimension array ")
print(oneDimensionArray)
print("The dimension of this array  ",oneDimensionArray.ndim)
print("The first element present in this array  ",oneDimensionArray[0])
print("The third element present in this array ",oneDimensionArray[2])
print("The sum of the element present in the 2nd and 3 rd index is ",oneDimensionArray[2]+oneDimensionArray[3])

This is my one dimension array 
[1 2 3 4 5]
The dimension of this array   1
The first element present in this array   1
The third element present in this array  3
The sum of the element present in the 2nd and 3 rd index is  7


In [ ]:
# Creating 2-d array
import numpy as np
twoDimensionArray = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("This is my 2-d array")
print(twoDimensionArray)
print("Displayig 1st row : ",twoDimensionArray[0])
print("Displaying 2nd row : ",twoDimensionArray[1])
print("Displaying 1st element of the first row ",twoDimensionArray[0,0])
print("Displaying 3rd element of the second row ",twoDimensionArray[1,3])

This is my 2-d array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Displayig 1st row :  [1 2 3 4 5]
Displaying 2nd row :  [ 6  7  8  9 10]
Displaying 1st element of the first row  1
Displaying 3rd element of the second row  9


In [ ]:
# Creating 3-d array
import numpy as np
threeDimensionArray = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("This is your 3-d array")
print(threeDimensionArray)
print("THE DIMENSION OF THIS ARRAY IS ",threeDimensionArray.ndim)
print("Displaying the first row of this array ",threeDimensionArray[0,0])
print("Displaying the third row of this array ",threeDimensionArray[0,2])
print("Displaying second element of third row ", threeDimensionArray[0,2,1])

This is your 3-d array
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
THE DIMENSION OF THIS ARRAY IS  3
Displaying the first row of this array  [1 2 3]
Displaying the third row of this array  [7 8 9]
Displaying second element of third row  8


In [ ]:
# Array Slicing 
import numpy as np
oneDimensionArray = np.array([1,2,3,4,5,6,7,8,9,10])
print("Your array is : ")
print(oneDimensionArray)
print("The dimension of this array is : ",oneDimensionArray.ndim)
print("Displaying element from 3rd to 6th index ",oneDimensionArray[3:7])
print("Displaying all element after 5th element of this array ",oneDimensionArray[5:])
print("Displaying all elements before 5th element of this ARRAY ",oneDimensionArray[:5])


Displaying all elements before 5th element of this ARRAY  [ 7  9 11 13 15]


In [ ]:
# Copy and View
import numpy as np
OriginalArray= np.array([1,2,3,4,56])
print(OriginalArray)


Original Array :  [1 2 3 4]
Original Array : [1 2 3 4]
Copied Array :  [600   2   3   4]


In [ ]:
# copy and View
import numpy as np
OriginalArray = np.array([1,2,3,4])
CopiedArray = OriginalArray.view()
print("This is the Original Array : ",OriginalArray)
print("Changes Applying to copied array :")
CopiedArray[0] = 100
print("This is the Original Array : ",OriginalArray)
print("This is the Copied Array : ",CopiedArray)

This is the Original Array :  [1 2 3 4]
Changes Applying to copied array :
This is the Original Array :  [100   2   3   4]
This is the Copied Array :  [100   2   3   4]


In [ ]:
# Numpy Iteration for 1-d array
import numpy as np 
oneDimensionArray = np.array([1,2,3,4,5])
for i in oneDimensionArray:
  print(i)

1
2
3
4
5


In [ ]:
# numpy iteration for 2-d array
import numpy as np 
twoDimensionArray = np.array([[1,2],[3,4]])
for i in twoDimensionArray:
  print(i)

[1 2]
[3 4]


In [ ]:
# numpy iteration for 2-d array to get exact value
import numpy as np 
twoDimensionArray = np.array([[1,2],[3,4]])
for i in twoDimensionArray:
  for j in i:
    print(j)

1
2
3
4


In [ ]:
# Numpy iteration for 3-d array
import numpy as np 
threeDimensionalArray = np.array([[[1,2],[3,4],[5,6]]])
for i in threeDimensionalArray:
  print(i)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Numpy iteration for 3-d array
import numpy as np 
threeDimensionalArray = np.array([[[1,2],[3,4],[5,6]]])
for i in threeDimensionalArray:
  for j in i:
    for k in j:
      print(k)

1
2
3
4
5
6


In [ ]:
# Numpy iteration using nditer() function
import numpy as np 
threeDimensionalArray = np.array([[[1,2],[3,4],[5,6]]])
for i in np.nditer(threeDimensionalArray):
  print(i)

1
2
3
4
5
6


In [ ]:
# Numpy Joins (Join 1-d Array) using concatenate() function
import numpy as np 
firstArray= np.array([1,2])
print("This is the first array : ",firstArray)
secondArray = np.array([3,4])
print("This is the second array : ",secondArray)
print("After Joining two array : ",np.concatenate((firstArray,secondArray)))

This is the first array :  [1 2]
This is the second array :  [3 4]
After Joining two array :  [1 2 3 4]


In [ ]:
# Numpy Joins (Join 2-d Array) using concatenate() function axis=1
import numpy as np 
firstArray= np.array([[1,2],[3,4]])
print("This is the first array : \n",firstArray)
secondArray = np.array([[5,6],[7,8]])
print("This is the second array : \n",secondArray)
print("After joining two array :\n",np.concatenate((firstArray, secondArray),axis=1))

This is the first array : 
 [[1 2]
 [3 4]]
This is the second array : 
 [[5 6]
 [7 8]]
After joining two array :
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Numpy Joins (Join 2-d Array) using concatenate() function axis=0
import numpy as np 
firstArray= np.array([[1,2],[3,4]])
print("This is the first array : \n",firstArray)
secondArray = np.array([[5,6],[7,8]])
print("This is the second array : \n",secondArray)
print("After joining two array :\n",np.concatenate((firstArray, secondArray),axis=0))

This is the first array : 
 [[1 2]
 [3 4]]
This is the second array : 
 [[5 6]
 [7 8]]
After joining two array :
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Numpy Joins using stack() function
import numpy as np 
firstArray = np.array([1,11,111])
print("First Array  = ",firstArray)
secondArray = np.array([2,22,222])
print("Second Array = ",secondArray)
print("After Joining two array : \n",np.stack((firstArray, secondArray)))

First Array  =  [  1  11 111]
Second Array =  [  2  22 222]
After Joining two array : 
 [[  1  11 111]
 [  2  22 222]]


In [ ]:
# Numpy Joins using hstack() function
import numpy as np
firstArray = np.array([1,2,3])
print("The first array is : ",firstArray)
secondArray = np.array([6,7,8])
print("The second array is : ",secondArray)
print("After joining two array : ",np.hstack((firstArray, secondArray)))

The first array is :  [1 2 3]
The second array is :  [6 7 8]
After joining two array :  [1 2 3 6 7 8]


In [ ]:
# Numpy Splitting
import numpy as np
array = np.array([1,2,3,4,5,6,7,8,9,10])
print("The array is : ",array)
# Splitting array into 3 parts
print("After Splitting : ",np.array_split(array, 3))

The array is :  [ 1  2  3  4  5  6  7  8  9 10]
After Splitting :  [array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


In [ ]:
# Numpy Search
import numpy as np 
array = np.array([1,2,3,6,11,12,27])
print("The array is : ",array)
# Find all the index where value is divisible by 3 exists
var = np.where(array % 3 == 0)
print(var)

The array is :  [ 1  2  3  6 11 12 27]
(array([2, 3, 5, 6]),)


In [ ]:
# Numpy Sorting
import numpy as np
array = np.array(["Yubaraj","Ayush","Muskan","Sagar","Priya"])
print("The Unsorted array is : ",array)
print("The Sorted Array is : ",np.sort(array))

The Unsorted array is :  ['Yubaraj' 'Ayush' 'Muskan' 'Sagar' 'Priya']
The Sorted Array is :  ['Ayush' 'Muskan' 'Priya' 'Sagar' 'Yubaraj']
